### PR TITLE
Major UI/UX upgrade!

### PR DESCRIPTION
**Pull request by daryll-ko**
# Updates

- The Events and Projects pages now look cleaner; events can now be filtered by type.
- The Home page is now maroon-themed.
- All pages are now fully responsive!
- Instead of a full-blown contact form, I've opted to just include a `mailto` link in the socials section in the footer.
- I made many minor stylistic changes here and there, but in general, sections should be more organized and nice to look at now.

# To-do

Now that the UI/UX part is practically done (we just need to hydrate the site with the latest data we have), most future changes are going to be DX-related:

- **Refactoring**: There are a number of optimizations I can think of for the repo's structure as a whole. Refactoring will also help make the in-depth docs more organized and easy to follow.
- **Dev documentation**: Once I'm happy with how things are laid out, I can fully flesh out the details I need to include in the dev docs.
- **Animations**: I'm thinking of replacing GSAP with Framer Motion for the different animations we use on the site. I plan to give this more consideration once I have the dev documentation down (I might omit GSAP in the dev docs to take the migration idea into account)
- **Testing**: I'll add end-to-end tests (using Playwright) to make sure things are stable. I might also include unit tests (using Jest) if I find them necessary.

### CODE REVIEW

**Comment by Qubits-01** [comment]
I also agree with using Framer Motion instead 👍

**Comment by Qubits-01** [comment]
Also, the UI/UX changes look better than before. 
Just a suggestion, can we also add a SHIMMER effect as a temporary placeholder for the images when they are still loading/downloading? (in the Team, Events, and Projects section). This is just optional though. Let me know what you think.

**Comment by Qubits-01** [comment]
> Also, the UI/UX changes look better than before. Just a suggestion, can we also add a SHIMMER effect as a temporary placeholder for the images when they are still loading/downloading? (in the Team, Events, and Projects section). This is just optional though. Let me know what you think.

Oh by the way, this optional UI improvement can be made in the next PR.

**Comment by daryll-ko** [comment]
I'll see what I can do about the shimmer effect; maybe I can also look into reducing the load times themselves.

**Review by Qubits-01 — APPROVED** [review]

**Pull request merged**
